services:
  trackoss:
    build: .
    ports:
      - '8080:80'
    container_name: trackoss-app
    restart: unless-stopped
    environment:
      MAP_TILE_PROXY_BASE_URL: 'http://backend:8080/api/map-proxy'
      VALHALLA_URL: 'http://valhalla:8002'
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
